// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.1
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SentinelService_SendError_FullMethodName = "/pb.SentinelService/SendError"
)

// SentinelServiceClient is the client API for SentinelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelServiceClient interface {
	SendError(ctx context.Context, in *ErrorInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sentinelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelServiceClient(cc grpc.ClientConnInterface) SentinelServiceClient {
	return &sentinelServiceClient{cc}
}

func (c *sentinelServiceClient) SendError(ctx context.Context, in *ErrorInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SentinelService_SendError_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentinelServiceServer is the server API for SentinelService service.
// All implementations must embed UnimplementedSentinelServiceServer
// for forward compatibility
type SentinelServiceServer interface {
	SendError(context.Context, *ErrorInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedSentinelServiceServer()
}

// UnimplementedSentinelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSentinelServiceServer struct {
}

func (UnimplementedSentinelServiceServer) SendError(context.Context, *ErrorInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendError not implemented")
}
func (UnimplementedSentinelServiceServer) mustEmbedUnimplementedSentinelServiceServer() {}

// UnsafeSentinelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelServiceServer will
// result in compilation errors.
type UnsafeSentinelServiceServer interface {
	mustEmbedUnimplementedSentinelServiceServer()
}

func RegisterSentinelServiceServer(s grpc.ServiceRegistrar, srv SentinelServiceServer) {
	s.RegisterService(&SentinelService_ServiceDesc, srv)
}

func _SentinelService_SendError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).SendError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_SendError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).SendError(ctx, req.(*ErrorInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// SentinelService_ServiceDesc is the grpc.ServiceDesc for SentinelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentinelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SentinelService",
	HandlerType: (*SentinelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendError",
			Handler:    _SentinelService_SendError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
